title: Yavelemira
tagline: 'A beautiful woman'
description: 'My thoughtsies, my world, and my buba.'
url: https://yavelemira.github.io
baseurl: /

author:
  name: 'Yavelemira'
  url: https://www.linkedin.com/in/maria-stroganova/

paginate: 5

# Plugins

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

github:
  repo: https://github.com/yavelemira/yavelemira.github.io
