title: yavelemira
tagline: 'ubiquitous okay'
description: 'my random thoughtsies'
url: https://yavelemira.com
baseurl: /

author:
  name: 'Yavelemira'
  url: https://www.linkedin.com/in/maria-stroganova/

# Plugins

plugins:
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

github:
  repo: https://github.com/yavelemira/yavelemira.github.io
